Python-lessons/django-projects/first_template/app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('blog/', views.blog, name='blog'),
    path('product/', views.product, name='product'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('support/', views.support, name='support'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('docs/', views.docs, name='docs'),
]

Python-lessons/django-projects/first_template/first_template/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Python-lessons/django-projects/first_template/app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Categories'

class Author(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(default='', blank=False)
    some = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    address = models.CharField(default='', max_length=100)
    user_image = models.ImageField(upload_to='author_images', blank=True)
    joined_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField( auto_now_add=True)
    username = models.CharField(max_length=100)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Authors'

class Hash(models.Model):
    hash_name = models.CharField(max_length=100)
    def __str__(self):
        return self.hash_name

class Card(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    price = models.IntegerField(default=0)
    discount = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    author = models.ForeignKey('Author', on_delete=models.CharField)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']
        verbose_name = 'card'
        verbose_name_plural = 'cards'

class Blog(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='blog_images/')
    hash_tag = models.ManyToManyField('Hash')
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    post_little_img = models.ImageField(upload_to='blog_images/60x60/')

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'

Python-lessons/django-projects/first_template/app/views.py
from django.shortcuts import render
from .models import Card, Blog
# Create your views here.

def index(request):
    return render(request, 'index.html')

def contact(request):
    return render(request, 'contact.html')

def blog(request):
    blogs = Blog.objects.all()
    return render(request, 'blog.html', {'blogs': blogs})

def product(request):
    cards = Card.objects.all()
    context = {
        'cards': cards
    }
    return render(request, 'product.html', context)

def product_detail(request, slug):
    card = Card.objects.get(slug=slug)
    context = {
        'card': card
    }
    return render(request, 'product-details.html', context)

def contact(request):
    return render(request, 'contact.html')

def support(request):
    return render(request, 'support.html')

def about(request):
    return render(request, 'about.html')

def docs(request):
    return render(request, 'documentation.html')

Python-lessons/django-projects/first_template/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Markit - Digital Marketplace HTML5 Template</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Place favicon.ico in the root directory -->
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="/static/assets/img/favicon.png"
    />
    <!-- CSS here -->
    <link rel="stylesheet" href="/static/assets/css/preloader.css" />
    <link rel="stylesheet" href="/static/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/assets/css/slick.css" />
    <link rel="stylesheet" href="/static/assets/css/meanmenu.css" />
    <link rel="stylesheet" href="/static/assets/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="/static/assets/css/animate.min.css" />
    <link rel="stylesheet" href="/static/assets/css/backToTop.css" />
    <link rel="stylesheet" href="/static/assets/css/jquery.fancybox.min.css" />
    <link rel="stylesheet" href="/static/assets/css/fontAwesome5Pro.css" />
    <link rel="stylesheet" href="/static/assets/css/elegantFont.css" />
    <link rel="stylesheet" href="/static/assets/css/default.css" />
    <link rel="stylesheet" href="/static/assets/css/style.css" />
    <style>
      article {
        max-width: 500px;
      }
    </style>
  </head>

  <body>
    <!--[if lte IE 9]>
      <p class="browserupgrade">
        You are using an <strong>outdated</strong> browser. Please
        <a href="/static/https://browsehappy.com/">upgrade your browser</a> to
        improve your experience and security.
      </p>
    <![endif]-->

    <!-- Add your site or application content here -->

    <!-- pre loader area start -->
    <div id="loading">
      <div id="loading-center">
        <div id="loading-center-absolute">
          <div class="object" id="object_one"></div>
          <div class="object" id="object_two" style="left: 20px"></div>
          <div class="object" id="object_three" style="left: 40px"></div>
          <div class="object" id="object_four" style="left: 60px"></div>
          <div class="object" id="object_five" style="left: 80px"></div>
        </div>
      </div>
    </div>
    <!-- pre loader area end -->

    <!-- back to top start -->
    <div class="progress-wrap">
      <svg
        class="progress-circle svg-content"
        width="100%"
        height="100%"
        viewBox="-1 -1 102 102"
      >
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
      </svg>
    </div>
    <!-- back to top end -->

    <!-- header area start -->
    <header>
      <div class="header__area white-bg" id="header-sticky">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-4 col-6">
              <div class="logo">
                <a href="/">
                  <img src="/static/assets/img/logo/logo.png" alt="logo" />
                </a>
              </div>
            </div>
            <div class="col-xxl-8 col-xl-8 col-lg-8 d-none d-lg-block">
              <div class="main-menu">
                <nav id="mobile-menu">
                  <ul>
                    <li>
                      <a href="/">Home</a>
                    </li>
                    <li>
                      <a href="{% url 'app:product' %}">Product</a>
                    </li>
                    <li><a href="{% url 'app:support' %}">Support</a></li>
                    <li><a href="{% url 'app:about' %}">About</a></li>
                    <li><a href="{% url 'app:docs' %}">Documentation</a></li>
                    <li>
                      <a href="{% url 'app:blog' %}">Blog</a>
                    </li>
                    <li><a href="{% url 'app:contact' %}">Contact</a></li>
                  </ul>
                </nav>
              </div>
            </div>
            <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-8 col-6">
              <div
                class="header__action d-flex align-items-center justify-content-end"
              >
                <div class="sidebar__menu d-lg-none">
                  <div class="sidebar-toggle-btn" id="sidebar-toggle">
                    <span class="line"></span>
                    <span class="line"></span>
                    <span class="line"></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- header area end -->
    {% block content %} {% endblock %}
    <!-- footer area start -->
    <footer>
      <div class="footer__area footer-bg">
        <div class="footer__top pt-90 pb-50">
          <div class="container">
            <div class="row">
              <div class="col-xxl-3 col-xl-3 col-lg-3 col-md-3 col-sm-4">
                <div
                  class="footer__widget mb-40 wow fadeInUp"
                  data-wow-delay=".3s"
                >
                  <div class="footer__widget-head mb-35">
                    <h4 class="footer__widget-title">Follow our Socials</h4>
                  </div>
                  <div class="footer__widget-content">
                    <div class="footer__social mb-30">
                      <ul>
                        <li>
                          <a href="/static/#" class="fb"
                            ><i class="fab fa-facebook-f"></i
                          ></a>
                        </li>
                        <li>
                          <a href="/static/#" class="tw"
                            ><i class="fab fa-twitter"></i
                          ></a>
                        </li>
                        <li>
                          <a href="/static/#" class="pin"
                            ><i class="fab fa-pinterest-p"></i
                          ></a>
                        </li>
                      </ul>
                    </div>
                    <div class="footer__lang">
                      <span><a href="/static/#">US</a> English</span>
                      <span><a href="/static/#">ES</a> Spanish</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-2 col-sm-4">
                <div
                  class="footer__widget mb-40 wow fadeInUp"
                  data-wow-delay=".5s"
                >
                  <div class="footer__widget-head">
                    <h4 class="footer__widget-title">Products</h4>
                  </div>
                  <div class="footer__widget-content">
                    <div class="footer__link">
                      <ul>
                        <li><a href="/static/#">Tutor LMS </a></li>
                        <li><a href="/static/#">WP Mega Menu </a></li>
                        <li><a href="/static/#">WP Page Builder </a></li>
                        <li><a href="/static/#">Themes</a></li>
                        <li><a href="/static/#">Interactions</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xxl-3 col-xl-3 col-lg-3 col-md-3 col-sm-4">
                <div
                  class="footer__widget mb-40 wow fadeInUp footer__pl"
                  data-wow-delay=".7s"
                >
                  <div class="footer__widget-head">
                    <h4 class="footer__widget-title">Resources</h4>
                  </div>
                  <div class="footer__widget-content">
                    <div class="footer__link">
                      <ul>
                        <li><a href="/static/#">Promotion </a></li>
                        <li><a href="/static/#">Submit Content</a></li>
                        <li><a href="/static/#">Resources</a></li>
                        <li><a href="/static/#">Design System</a></li>
                        <li><a href="/static/#">Expert</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-2 col-sm-4">
                <div
                  class="footer__widget mb-40 wow fadeInUp"
                  data-wow-delay=".9s"
                >
                  <div class="footer__widget-head">
                    <h4 class="footer__widget-title">Products</h4>
                  </div>
                  <div class="footer__widget-content">
                    <div class="footer__link">
                      <ul>
                        <li><a href="/static/#">About Us</a></li>
                        <li><a href="/static/#">Blog</a></li>
                        <li><a href="/static/#">Support</a></li>
                        <li><a href="/static/#">Pricing</a></li>
                        <li><a href="/static/#">Contact</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-2 col-sm-4">
                <div
                  class="footer__widget mb-40 wow fadeInUp"
                  data-wow-delay="1.2s"
                >
                  <div class="footer__widget-head">
                    <h4 class="footer__widget-title">Community</h4>
                  </div>
                  <div class="footer__widget-content">
                    <div class="footer__link">
                      <ul>
                        <li><a href="/static/#">Forums</a></li>
                        <li><a href="/static/#">Community</a></li>
                        <li><a href="/static/#">Meetups</a></li>
                        <li><a href="/static/#">Jobs</a></li>
                        <li><a href="/static/#">Careers</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="footer__bottom">
          <div class="container">
            <div class="footer__bottom-inner">
              <div class="row">
                <div class="col-xxl-6 col-xl-6 col-md-6">
                  <div
                    class="footer__copyright wow fadeInUp"
                    data-wow-delay=".5s"
                  >
                    <p>
                      Copyright © 2021 All Rights Reserved, Design by
                      <a href="/static/#">Theme Pure</a>
                    </p>
                  </div>
                </div>
                <div class="col-xxl-6 col-xl-6 col-md-6">
                  <div
                    class="footer__bottom-link wow fadeInUp text-md-end"
                    data-wow-delay=".8s"
                  >
                    <ul>
                      <li><a href="/static/#">Licence</a></li>
                      <li><a href="/static/#">Privacy Policy </a></li>
                      <li><a href="/static/#">Affiliate Notice</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- footer area end -->

    <!-- JS here -->
    <script src="{% static 'assets/js/vendor/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.meanmenu.js' %}"></script>
    <script src="{% static 'assets/js/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/parallax.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/backToTop.js' %}"></script>
    <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'assets/js/ajax-form.js' %}"></script>
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>